In [4]:
import numpy as np

In [25]:
np1=np.array([[1,2],[6,7],[8,9]])

In [26]:
np1.ndim

2

In [27]:
np1

array([[1, 2],
       [6, 7],
       [8, 9]])

In [28]:
np1.itemsize

4

In [30]:
np1.size

6

In [31]:
np1.shape

(3, 2)

In [32]:
np1=np.array([[1,2],[6,7],[8,9]],dtype=complex)

In [33]:
np1

array([[1.+0.j, 2.+0.j],
       [6.+0.j, 7.+0.j],
       [8.+0.j, 9.+0.j]])

In [35]:
o=np.zeros((3,4))
o

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
n=np.ones((3,4),dtype=int)
n

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
n.size

12

In [41]:
l=np.arange(1,5)
l

array([1, 2, 3, 4])

In [42]:
l= np.arange(1,100,step=3)

In [43]:
l

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [47]:
b=np.linspace(1,10,30)
b

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [51]:
n.reshape(2,6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [52]:
n

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [53]:
n.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
n.min()

1

In [55]:
n.max()

1

In [56]:
n.sum()

12

In [61]:
np1=np.array([[1,2],[6,7],[8,9]],dtype=int)
np1

array([[1, 2],
       [6, 7],
       [8, 9]])

In [62]:
np1.sum(axis=1)

array([ 3, 13, 17])

In [63]:
np1.sum(axis=0)

array([15, 18])

In [65]:
np.sqrt(np1).round(1)

array([[1. , 1.4],
       [2.4, 2.6],
       [2.8, 3. ]])

In [66]:
#standard deviation
np.std(np1)

2.9860788111948193

In [67]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [68]:
a+b

array([[ 6,  8],
       [10, 12]])

In [69]:
a*b

array([[ 5, 12],
       [21, 32]])

In [70]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [71]:
x=np.arange(0,10,2)

In [72]:
x

array([0, 2, 4, 6, 8])

In [73]:
x[0:4]

array([0, 2, 4, 6])

In [75]:
x[-2]

6

In [84]:
x=np.arange(11,20)
x=x.reshape(3,3)
x

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [83]:
x[0:2,2]

array([13, 16])

In [93]:
for i in x.flat:
    print(i)

11
12
13
14
15
16
17
18
19


In [102]:
for j in (x.reshape(1,9)):
    print(f'{j}\n')

[11 12 13 14 15 16 17 18 19]



In [108]:
a=np.arange(0,6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [112]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [113]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [118]:
 a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [127]:
b=np.arange(30).reshape(15,2)
np.vsplit(b,5)

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[18, 19],
        [20, 21],
        [22, 23]]),
 array([[24, 25],
        [26, 27],
        [28, 29]])]

In [131]:
filt=b>20
b[filt]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [132]:
y=np.arange(12).reshape(3,4)

In [133]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
for i in y:
    for j in i:
        print(j)
#for i in y.flatten:
    #pritn(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [140]:
for i in np.nditer(y,op_flags=['readwrite']):
    i[...]=i*i


In [141]:
y

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [156]:
a=[]
for i in y.flatten():
    i=pow(i,0.5).astype(int)
    a.append(i)
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [158]:
a,y

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 array([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]]))

In [171]:
a=np.asarray(a).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])